version: 1.0

steps:
  - name: download_dataset
    type: cli
    cmd: |
      # download image dataset from huggingface
      huggingface-cli download --repo-type dataset Azu/Handwritten-Mathematical-Expression-Convert-LaTeX --local-dir ./ --include data.zip

      # unzip
      unzip -q -o data.zip -d data

      # convert all BMP images to JPG
      magick mogrify -format jpg -quality 90 -path ./data/2019 ./data/2019/*.bmp
    outputFilename: data

  - name: analyze_math_image
    type: prompt
    model: ollama:qwen2.5vl:3b
    # model: lmstudio:gemma-3-4b-it
    maxResults: 10
    prompt: |
      Image contains mathematical formula. Convert to Latex. Don't add any extra information
    imagePath: |
      ./data/2019/*.jpg

  - name: explain_math
    type: prompt
    model: ollama:qwen2.5vl:3b
    # model: lmstudio:gemma-3-4b-it
    maxResults: 10
    prompt: |
      Given the following formula, break down the steps needed to understand or solve it. Start by identifying the type of mathematical expression it is (e.g., complex numbers, exponential form, etc.), then explain each term and operation, and proceed to derive or simplify as appropriate. Show your reasoning at each step. Format your response in clear Markdown, using headings, bullet points, and LaTeX for math where helpful.
      Formula: {{.analyze_math_image}}
