version: 1.0

# Declare required environment variables (optional but recommended)
# These will be validated before config processing - program fails fast if missing
# envVars:
#   - REQUIRED_FILE
#   - DOWNLOAD_DIR
#   - PROVIDER
#   - MODEL

steps:
  - name: download_prompts
    run: hf download --repo-type dataset fka/awesome-chatgpt-prompts --local-dir ./ --include $REQUIRED_FILE
    outputFilename: $REQUIRED_FILE
    workDir: $DOWNLOAD_DIR

  - name: convert_to_jsonl
    run: |
      duckdb -c "
      COPY (
        SELECT act, prompt
        FROM read_csv_auto('../$DOWNLOAD_DIR/$REQUIRED_FILE', header=true)
      ) TO 'all_prompts.jsonl' (FORMAT JSON);
      "
    outputFilename: all_prompts.jsonl
    workDir: processed

  - name: analyze_complexity
    model: $PROVIDER:$MODEL
    maxResults: convert_to_jsonl.$length
    systemPrompt: |
      You are an expert in analyzing instructional prompts and assessing their complexity.
      Rate prompts based on:
      - Cognitive load required
      - Domain expertise needed
      - Number of constraints or requirements
      - Creative vs analytical demands
    prompt: |
      Analyze this ChatGPT role-playing prompt and rate its complexity:

      Role: {{.convert_to_jsonl.act}}
      Prompt: {{.convert_to_jsonl.prompt}}

      Provide a complexity rating and explain your reasoning.
    jsonSchema:
      type: object
      properties:
        complexity:
          type: string
          enum: [simple, moderate, complex]
          description: "Overall complexity rating"
        reasoning:
          type: string
          description: "Explanation for the complexity rating"
        key_challenges:
          type: array
          items:
            type: string
          description: "Main challenges in fulfilling this prompt"
      required:
        - complexity
        - reasoning
        - key_challenges
