version: 1.0

steps:
  - name: download_dataset
    type: shell
    cmd: |
      hf download --repo-type dataset TIGER-Lab/MathInstruct --local-dir ./ --include MathInstruct.json
    outputFilename: MathInstruct.json

  - name: math_problems_10
    type: shell
    cmd: |
      jq -c '.[:10][]' ./MathInstruct.json > ./10_math_problems.jsonl
    outputFilename: 10_math_problems.jsonl

  - name: solve_with_reasoning
    type: prompt
    model: ollama:llama3.2
    maxResults: math_problems_10.$length
    modelConfig:
      temperature: 0.7
    prompt: |
      Solve the following math problem step by step. Break down your solution into clear reasoning steps.
      Each step should have an explanation of what you're doing and the output/result of that step.

      Problem: {{.math_problems_10.instruction}}
    jsonSchema:
      type: object
      properties:
        steps:
          type: array
          items:
            type: object
            properties:
              explanation:
                type: string
                description: "Explanation of what this step does"
              output:
                type: string
                description: "The result or output of this step"
            required:
              - explanation
              - output
          description: "List of reasoning steps to solve the problem"
        final_answer:
          type: string
          description: "The final answer to the problem"
      required:
        - steps
        - final_answer
