name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-n-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-version: ["1.25.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: make install

      - name: golangci-lint
        if: runner.os != 'Windows'
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: --verbose

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Check datamatic version
        run: |
          ./datamatic --version

      - name: Setup Ollama
        if: runner.os == 'Linux'
        uses: ai-action/setup-ollama@v1

      - name: Run datamatic with ollama
        if: runner.os == 'Linux'
        run: |
          ollama pull llama3.2
          # for simplicity, we set maxResults == 1
          sed -i -e 's/maxResults: 10/maxResults: 1/g' ./examples/v1/3.\ complex\ json,\ linked\ steps/config.yaml
          ./datamatic --config ./examples/v1/3.\ complex\ json,\ linked\ steps/config.yaml --verbose
          cat ./dataset/text_about_country.jsonl | jq
